<a href="https://colab.research.google.com/github/AvinashTiwari/MachineLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
b.ndim

1

In [12]:
c=np.arry(1,2)

AttributeError: ignored

In [13]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [15]:
c=np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
c.dtype

dtype('complex128')

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])