<a href="https://colab.research.google.com/github/AvinashTiwari/MachineLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
b.ndim

1

In [12]:
##c=np.arry(1,2)

In [13]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [14]:
c=np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
c.dtype

dtype('complex128')

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [18]:
a=np.arange(1,20,2.5)
a

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [ ]:
a=np.linspace(1,20,6)
a

In [19]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)
a
b

array([0, 1, 2, 3])

In [23]:
c = a-b
c

array([20, 29, 38, 47])

In [24]:
c = a+b
c

array([20, 31, 42, 53])

In [26]:
c**2
c

array([20, 31, 42, 53])

In [27]:
a<35

array([ True,  True, False, False])

In [28]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [29]:
A@B

array([[5, 4],
       [3, 4]])

In [30]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [31]:
b = np.random.random((2,3))
b

array([[0.21519268, 0.8523301 , 0.10623665],
       [0.70925222, 0.52714434, 0.28080835]])

In [33]:
a*=3
a

array([180, 270, 360, 450])

ValueError: ignored