<a href="https://colab.research.google.com/github/AvinashTiwari/MachineLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
b.ndim

1

In [11]:
##c=np.arry(1,2)

In [12]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [13]:
c=np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
c.dtype

dtype('complex128')

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [17]:
a=np.arange(1,20,2.5)
a

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [18]:
a=np.linspace(1,20,6)
a

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [19]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
a = np.array([20,30,40,50])
b = np.arange(4)
a
b

array([0, 1, 2, 3])

In [22]:
c = a-b
c

array([20, 29, 38, 47])

In [23]:
c = a+b
c

array([20, 31, 42, 53])

In [24]:
c**2
c

array([20, 31, 42, 53])

In [25]:
a<35

array([ True,  True, False, False])

In [26]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [27]:
A@B

array([[5, 4],
       [3, 4]])

In [28]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [29]:
b = np.random.random((2,3))
b

array([[0.60824668, 0.70395871, 0.72357656],
       [0.21409411, 0.27142856, 0.97783086]])

In [30]:
a*=3
a

array([ 60,  90, 120, 150])

In [31]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.sum()
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [34]:
a.sum(axis=1)

array([ 6, 22, 38])

In [35]:
a.max(axis=0)

array([ 8,  9, 10, 11])

In [36]:
a.min(axis=1)

array([0, 4, 8])

In [37]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [38]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [39]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [41]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [42]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [44]:
a[3]

27

In [45]:
a[2:5]

array([ 8, 27, 64])

In [46]:
a[3:6]

array([ 27,  64, 125])

In [47]:
a[:6:2]

array([ 0,  8, 64])

In [48]:
a[:6:2]-1000

array([-1000,  -992,  -936])

In [49]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [50]:
for i in a:
  print(1**(1/3.))

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [51]:
def f(x,y):
  return 10*x+y


In [52]:
b=np.fromfunction(f,(6,4))
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.],
       [50., 51., 52., 53.]])

In [53]:
b[2,3]

23.0

In [54]:
b[0:5,1]

array([ 1., 11., 21., 31., 41.])

In [55]:
b[1:3,1]

array([11., 21.])

In [56]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 9., 3., 6.],
       [2., 3., 8., 5.],
       [7., 2., 2., 2.]])

In [57]:
a.shape

(3, 4)

In [58]:
a.ravel()

array([8., 9., 3., 6., 2., 3., 8., 5., 7., 2., 2., 2.])

In [59]:
a.reshape(6,2)

array([[8., 9.],
       [3., 6.],
       [2., 3.],
       [8., 5.],
       [7., 2.],
       [2., 2.]])

In [60]:
a.T

array([[8., 2., 7.],
       [9., 3., 2.],
       [3., 8., 2.],
       [6., 5., 2.]])

In [61]:
a.T.shape

(4, 3)

In [62]:
a.resize(2,6)
a

array([[8., 9., 3., 6., 2., 3.],
       [8., 5., 7., 2., 2., 2.]])

In [63]:
a.reshape(4,3)

array([[8., 9., 3.],
       [6., 2., 3.],
       [8., 5., 7.],
       [2., 2., 2.]])

In [64]:
a.reshape(3,-1)

array([[8., 9., 3., 6.],
       [2., 3., 8., 5.],
       [7., 2., 2., 2.]])

In [65]:
a.reshape(2,-1)

array([[8., 9., 3., 6., 2., 3.],
       [8., 5., 7., 2., 2., 2.]])

In [66]:
a = np.floor(10*np.random.random((2,2)))
a

array([[0., 2.],
       [5., 8.]])

In [67]:
b=np.floor(10*np.random.random((2,2)))
b

array([[6., 2.],
       [9., 4.]])

In [68]:
np.vstack((a,b))

array([[0., 2.],
       [5., 8.],
       [6., 2.],
       [9., 4.]])

In [69]:
np.hstack((a,b))

array([[0., 2., 6., 2.],
       [5., 8., 9., 4.]])

In [70]:
from numpy import newaxis
np.column_stack((a,b))

array([[0., 2., 6., 2.],
       [5., 8., 9., 4.]])

In [71]:
c = np.array([4,2])
d = np.array([4,2])
np.column_stack((c,d))

array([[4, 4],
       [2, 2]])

In [72]:
a = np.floor(10*np.random.random((2,12)))
a

array([[8., 2., 1., 1., 1., 4., 1., 2., 8., 2., 3., 6.],
       [2., 8., 0., 3., 8., 6., 7., 5., 7., 7., 8., 4.]])

In [76]:
np.hsplit(a,(3,4))

[array([[8., 2., 1.],
        [2., 8., 0.]]),
 array([[1.],
        [3.]]),
 array([[1., 4., 1., 2., 8., 2., 3., 6.],
        [8., 6., 7., 5., 7., 7., 8., 4.]])]

In [77]:
np.hsplit(a,3)

[array([[8., 2., 1., 1.],
        [2., 8., 0., 3.]]),
 array([[1., 4., 1., 2.],
        [8., 6., 7., 5.]]),
 array([[8., 2., 3., 6.],
        [7., 7., 8., 4.]])]