<a href="https://colab.research.google.com/github/AvinashTiwari/MachineLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
b.ndim

1

In [11]:
##c=np.arry(1,2)

In [12]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [13]:
c=np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
c.dtype

dtype('complex128')

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [17]:
a=np.arange(1,20,2.5)
a

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [18]:
a=np.linspace(1,20,6)
a

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [19]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
a = np.array([20,30,40,50])
b = np.arange(4)
a
b

array([0, 1, 2, 3])

In [22]:
c = a-b
c

array([20, 29, 38, 47])

In [23]:
c = a+b
c

array([20, 31, 42, 53])

In [24]:
c**2
c

array([20, 31, 42, 53])

In [25]:
a<35

array([ True,  True, False, False])

In [26]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [27]:
A@B

array([[5, 4],
       [3, 4]])

In [28]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [29]:
b = np.random.random((2,3))
b

array([[0.54875118, 0.54267947, 0.85267779],
       [0.91765121, 0.78527158, 0.34266264]])

In [30]:
a*=3
a

array([ 60,  90, 120, 150])

In [31]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.sum()
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [34]:
a.sum(axis=1)

array([ 6, 22, 38])

In [35]:
a.max(axis=0)

array([ 8,  9, 10, 11])

In [36]:
a.min(axis=1)

array([0, 4, 8])

In [37]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [38]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [39]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [41]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [42]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [44]:
a[3]

27

In [45]:
a[2:5]

array([ 8, 27, 64])

In [46]:
a[3:6]

array([ 27,  64, 125])

In [47]:
a[:6:2]

array([ 0,  8, 64])

In [48]:
a[:6:2]-1000

array([-1000,  -992,  -936])

In [49]:
a[: : -1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [50]:
for i in a:
  print(1**(1/3.))

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [51]:
def f(x,y):
  return 10*x+y


In [52]:
b=np.fromfunction(f,(6,4))
b

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.],
       [50., 51., 52., 53.]])

In [53]:
b[2,3]

23.0

In [54]:
b[0:5,1]

array([ 1., 11., 21., 31., 41.])

In [55]:
b[1:3,1]

array([11., 21.])

In [56]:
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 5., 4., 2.],
       [3., 3., 2., 2.],
       [5., 1., 2., 2.]])

In [57]:
a.shape

(3, 4)

In [58]:
a.ravel()

array([7., 5., 4., 2., 3., 3., 2., 2., 5., 1., 2., 2.])

In [59]:
a.reshape(6,2)

array([[7., 5.],
       [4., 2.],
       [3., 3.],
       [2., 2.],
       [5., 1.],
       [2., 2.]])

In [60]:
a.T

array([[7., 3., 5.],
       [5., 3., 1.],
       [4., 2., 2.],
       [2., 2., 2.]])

In [61]:
a.T.shape

(4, 3)

In [62]:
a.resize(2,6)
a

array([[7., 5., 4., 2., 3., 3.],
       [2., 2., 5., 1., 2., 2.]])

In [63]:
a.reshape(4,3)

array([[7., 5., 4.],
       [2., 3., 3.],
       [2., 2., 5.],
       [1., 2., 2.]])

In [64]:
a.reshape(3,-1)

array([[7., 5., 4., 2.],
       [3., 3., 2., 2.],
       [5., 1., 2., 2.]])

In [65]:
a.reshape(2,-1)

array([[7., 5., 4., 2., 3., 3.],
       [2., 2., 5., 1., 2., 2.]])

In [66]:
a = np.floor(10*np.random.random((2,2)))
a

array([[2., 9.],
       [3., 7.]])

In [67]:
b=np.floor(10*np.random.random((2,2)))
b

array([[3., 7.],
       [9., 6.]])

In [68]:
np.vstack((a,b))

array([[2., 9.],
       [3., 7.],
       [3., 7.],
       [9., 6.]])

In [69]:
np.hstack((a,b))

array([[2., 9., 3., 7.],
       [3., 7., 9., 6.]])

In [70]:
from numpy import newaxis
np.column_stack((a,b))

array([[2., 9., 3., 7.],
       [3., 7., 9., 6.]])

In [71]:
c = np.array([4,2])
d = np.array([4,2])
np.column_stack((c,d))

array([[4, 4],
       [2, 2]])

In [72]:
a = np.floor(10*np.random.random((2,12)))
a

array([[2., 9., 6., 5., 6., 4., 6., 8., 2., 6., 9., 7.],
       [8., 2., 2., 0., 8., 4., 7., 8., 0., 4., 2., 6.]])

In [73]:
np.hsplit(a,(3,4))

[array([[2., 9., 6.],
        [8., 2., 2.]]),
 array([[5.],
        [0.]]),
 array([[6., 4., 6., 8., 2., 6., 9., 7.],
        [8., 4., 7., 8., 0., 4., 2., 6.]])]

In [74]:
np.hsplit(a,3)

[array([[2., 9., 6., 5.],
        [8., 2., 2., 0.]]),
 array([[6., 4., 6., 8.],
        [8., 4., 7., 8.]]),
 array([[2., 6., 9., 7.],
        [0., 4., 2., 6.]])]

In [75]:
a = np.arange(12)
b=a
a is a


True

In [76]:
b.shape=3,4
a.shape

(3, 4)

In [77]:
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
c.flags.owndata

False

In [79]:
c.shape = 2,6
c.shape

(2, 6)

In [80]:
a.shape

(3, 4)

In [81]:
c[0,4] = 1234
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [82]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [83]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [84]:
i = np.array([1,1,3,8,5])
a[i]

array([ 1,  1,  9, 64, 25])

In [85]:
j = np.array([[3,4], [9,7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [86]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [88]:
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

In [89]:
a[[0,0,2]] +=1
a

array([3, 1, 4, 3, 4])

In [90]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [92]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [94]:
a[b]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])