<a href="https://colab.research.google.com/github/AvinashTiwari/MachineLearning/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 3)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.data

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
b.ndim

1

In [11]:
c=np.arry(1,2)

AttributeError: ignored

In [12]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [13]:
c=np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
c.dtype

dtype('complex128')

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [18]:
a=np.arange(1,20,2.5)
a

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [19]:
a=np.linspace(1,20,6)
a

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [22]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])